package com.galacticfiles;

/**
 * Provides information about bitcoin addresses generated by the site
 * a user can pay to to add funds to his account.
 *
 */
public class AddressInfo {

	private String address;
	private long createdon;
	private String totalReceived;

	/**
	 * The bitcoin address a user can pay to
	 * @return bitcoin address
	 */
	public String getAddress() {
		return address;
	}
	
	protected void setAddress(String address) {
		this.address = address;
	}
	
	/**
	 * The number of milliseconds since January 1, 1970, 00:00:00 GMT when
	 * the address was created
	 * @return time in milliseconds
	 */
	public long getCreatedon() {
		return createdon;
	}
	
	protected void setCreatedon(long createdon) {
		this.createdon = createdon;
	}
	
	/**
	 * The total amount confirmed that has been paid to this address
	 * @return the bitcoin amount
	 */
	public String getTotalReceived() {
		return totalReceived;
	}
	
	protected void setTotalReceived(String totalReceived) {
		this.totalReceived = totalReceived;
	}
	
}
